import './Disclaimer.css';

const Disclaimer = () =>{
    return (
        <div className='footer'>
            <text>Disclaimer: This software is under development. Please consult with a doctor before acting on any decisions/inference generated by this tool.</text>
        </div>
    )
}

export default Disclaimer;